require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ProofOfConcept' do

  #FFMPEG
  pod 'react-native-ffmpeg/full-gpl-lts', :podspec => '../node_modules/react-native-ffmpeg/react-native-ffmpeg.podspec'

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'

  target 'ProofOfConceptTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ProofOfConcept-tvOS' do
  # Pods for ProofOfConcept-tvOS

  target 'ProofOfConcept-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
